### ISSUE TITLE
clockwork 

### ISSUE THREAD

**Issue by Vinnichenko-Ivan** [BurnerLab/mayday#2]
#include <SFML/Graphics.hpp>
 #include <iostream>
using namespace sf;
int main()
{
	int x=50,y=25;
	RenderWindow window(sf::VideoMode(640, 480), "ziben"); //увеличили для удобства размер окна
 
	
 
	Texture heroHeadt;//создаем объект Texture (текстура)
	heroHeadt.loadFromFile("images/mainhero/Front/Head.png");//загружаем картинку
 
	Sprite heroHead;//создаем объект Sprite(спрайт)
	heroHead.setTexture(heroHeadt);//передаём в него объект Texture (текстуры)
	heroHead.setPosition(x, y);//задаем начальные координаты появления спрайта
 	

	while (window.isOpen())	
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}
		std::cin>>x>>y;
        heroHead.setPosition(x, y);
		window.clear();
		window.draw(heroHead);//выводим спрайт на экран
		window.display();
	}
 
	return 0;
}

**Comment by Kuodos** [comment]
stop dat
